<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="MAIN_Fast" Id="{f3aabdab-143e-4e78-8800-ab31e3e5df70}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN_Fast
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN_Fast">
      <LineId Id="1" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>