<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_Setpoint_Generator" Id="{ba46414f-087c-4b1c-8465-4eeebd5edc8b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Setpoint_Generator
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="FB_Init" Id="{934b235d-9833-48db-b6f4-391752153908}">
      <Declaration><![CDATA[//FB_Init is always available implicitly and it is used primarily for initialization.
//The return value is not evaluated. For a specific influence, you can also declare the
//methods explicitly and provide additional code there with the standard initialization
//code. You can evaluate the return value.
METHOD FB_Init: BOOL
VAR_INPUT
    bInitRetains: BOOL; // TRUE: the retain variables are initialized (reset warm / reset cold)
    bInCopyCode: BOOL;  // TRUE: the instance will be copied to the copy code afterward (online change)   
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Cyclic" Id="{2bbf86ce-9f52-4111-bf2f-dbebf9a0a72b}">
      <Declaration><![CDATA[METHOD PUBLIC M_Cyclic
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Setpoint_Generator">
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="FB_Setpoint_Generator.FB_Init">
      <LineId Id="1" Count="0" />
    </LineIds>
    <LineIds Name="FB_Setpoint_Generator.M_Cyclic">
      <LineId Id="1" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>